### ISSUE TITLE
For AWS, default the EBS from 100 GB to 30GB

### ISSUE THREAD

**Issue by omenking** [forem/selfhost#21]
Its default is 100 GB and this means snapshots will take a long time when creating AMIs.
EBS snapshots are a common hidden cost that can add up quickly on AWS

```
  vars:
    fcos_arch: x86_64
    fcos_platform: aws
    fcos_format: vmdk.xz
    fcos_stream: stable
    fcos_aws_region: us-east-1
    fcos_aws_size: t3a.small
    fcos_aws_ebs_size: 100
    fcos_aws_profile: forem-selfhost
    butane_cleanup: true
    ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
```

Free Tier is 30 GB, So I would like to suggest this as the default.

<img width="888" alt="Screen Shot 2021-07-22 at 2 27 26 PM" src="https://user-images.githubusercontent.com/7776/126690720-941be06c-1ef7-4b37-9603-2af680e68d31.png">
